config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'users#index'

  get                    '/signup', to: 'users#new',               as: 'signup'
  post                   '/signup', to: 'users#create'

  get                     '/login', to: 'sessions#new'
  post                    '/login', to: 'sessions#create'
  delete                 '/logout', to: 'sessions#destroy'

  get              '/users/search', to: 'users#search'
  get     '/users/:username/:slug', to: 'users#connection',         as: 'user_connections'
  post         '/users/follow/:id', to: 'users#follow',             as: 'follow_user'
  post       '/users/unfollow/:id', to: 'users#unfollow',           as: 'unfollow_user'
  get               '/users/:slug', to: 'users#show',               as: 'user_show'

  post               '/microposts', to: 'microposts#create',        as: 'create_post'
  get          '/microposts/:slug', to: 'microposts#user_posts',    as: 'display_user_posts'
  get                '/microposts', to: 'microposts#all_posts',     as: 'display_all_posts'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/following.rb
class Following < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :author, foreign_key: :author_id, class_name: 'User'

  validates :text, presence: true, length: { maximum: 160 }
end

app/models/user.rb
class User < ApplicationRecord
  mattr_accessor :who_to_follow_offset, :current_user

  has_many :microposts, foreign_key: :author_id, dependent: :destroy

  has_many :followed, foreign_key: :follower_id, class_name: 'Following', dependent: :destroy
  has_many :followees, through: :followed, source: :followed

  has_many :following, foreign_key: :followed_id, class_name: 'Following', dependent: :destroy
  has_many :followers, through: :following, source: :follower

  has_many :followed_by_someone_you_follow, -> { where(id: current_user.followees).limit(1) },
           through: :following, source: :follower

  has_many :followed_by_someone_you_dont_follow,
           -> { where.not(id: [current_user] + current_user.followees).limit(3) },
           through: :following, source: :follower

  has_many :followed_by_someone_excluding_you, -> { where.not(id: current_user).limit(3) },
           through: :following, source: :follower

  validates :username, presence: true, length: { maximum: 20 }, uniqueness: true
  validates :full_name, presence: true, length: { maximum: 50 }

  def who_to_follow
    who_to_follow = User.where.not(id: [id] + Following.where(follower_id: id).pluck(:followed_id))
      .includes(:followed_by_someone_you_follow).order(:created_at)
      .reverse_order.limit(3).offset(who_to_follow_offset)

    if who_to_follow.length < 3 && User.where.not(id: [id] + Following
          .where(follower_id: id).pluck(:followed_id)).count > 3
      self.who_to_follow_offset = who_to_follow.empty? ? 0 : 3 - who_to_follow.length
      who_to_follow += User.where.not(id: [id] + Following.where(follower_id: id).pluck(:followed_id))
        .includes(:followed_by_someone_you_follow).order(:created_at)
        .reverse_order.limit(3 - who_to_follow.length).offset(0)
    end

    who_to_follow
  end

  def all_the_posts_for_timeline
    Micropost.where(author_id: [id] + followees.ids).includes(:author).order(:created_at).reverse_order
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  include ErrorsHelper
  include UsersHelper

  protect_from_forgery with: :exception
  before_action :authorized

  private

  def authorized
    redirect_to login_path unless logged_in?
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  def create
    post = current_user.microposts.create(micropost_params)

    if post.valid?
      @posts = current_user.all_the_posts_for_timeline
      render partial: 'microposts/posts'
    else
      @error = post.errors.messages[:text].first
      render partial: 'microposts/error'
    end
  end

  def user_posts
    user = User.find_by(username: params[:slug])
    @posts = user.microposts
    render partial: 'microposts/posts'
  end

  def all_posts
    @posts = current_user.microposts
    render partial: 'microposts/posts'
  end

  private

  def micropost_params
    params.require(:micropost).permit(:text)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only: %i[new create]

  def new
    redirect_to root_path if logged_in?
  end

  def create
    @user = User.find_by(username: login_params[:username])
    if @user
      User.current_user = @user
      log_in @user
      redirect_to root_path
    else
      flash.notice = 'Invalid username'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to login_path
  end

  private

  def login_params
    params.require(:session).permit(:username)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: %i[new create]

  def index
    User.who_to_follow_offset = 0
    User.current_user = current_user
    @posts = current_user.all_the_posts_for_timeline
    @who_to_follow = current_user.who_to_follow
  end

  def new
    redirect_to root_path if logged_in?
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.photo = Faker::Avatar.image(slug: params[:username], size: '100x100', format: 'jpg')
    @user.cover_image = Faker::LoremFlickr.image(size: '744x249', search_terms: ['nature'])

    if @user.save
      log_in @user
      redirect_to root_path
    else
      @user.username = @user.full_name = ''
      render 'new'
    end
  end

  def search
    User.who_to_follow_offset += 3
    @who_to_follow = current_user.who_to_follow
    render partial: 'users/index/who_to_follow'
  end

  def connection
    user = User.find_by(username: params[:username])
    User.current_user = user
    @headline = headline(user, params[:slug])

    if @headline.nil?
      redirect_to root_path
    else
      @user_list = user_list(user, params[:slug])
      @who_to_follow = user.who_to_follow
      render partial: 'users/connection/user_list'
    end
  end

  def follow
    Following.create(follower_id: current_user.id, followed_id: params[:id])
    redirect_to user_show_path(slug: User.find(params[:id]).username)
  end

  def unfollow
    Following.destroy(Following.where(follower_id: current_user.id, followed_id: params[:id]).first.id)
    redirect_to user_show_path(slug: User.find(params[:id]).username)
  end

  def show
    User.current_user = current_user
    @user = User.find_by(username: params[:slug])
    @posts = @user.microposts
    @who_to_follow = @user.followers.limit(3)
  end

  private

  def user_params
    params.require(:user).permit(:username, :full_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_svg(path)
    File.open("app/assets/images/svg/#{path}", 'rb') do |file|
      raw file.read
    end
  end
end

app/helpers/errors_helper.rb
module ErrorsHelper
  def login_username(flash)
    ' error' unless flash[:notice].nil?
  end

  def login_username_placeholder(flash)
    flash[:notice] unless flash[:notice].nil?
  end

  def username(user)
    ' error' unless user.errors[:username].nil?
  end

  def username_placeholder(user)
    user.errors.messages[:username].first unless user.errors[:username].empty?
  end

  def full_name(user)
    ' error' unless user.errors[:full_name].nil?
  end

  def full_name_placeholder(user)
    user.errors.messages[:full_name].first unless user.errors[:full_name].empty?
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def logged_in?
    !current_user.nil?
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    end
    @current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def headline(user, slug)
    if slug.eql?('following')
      user == current_user ? 'Your followees' : "#{user.full_name} followees"
    elsif slug.eql?('followers')
      user == current_user ? 'Your followers' : "#{user.full_name} followers"
    end
  end

  def user_list(user, slug)
    if slug.eql?('following')
      @user_list = user.followees.includes(:followed_by_someone_you_follow)
    elsif slug.eql?('followers')
      @user_list = user.followers.includes(:followed_by_someone_you_follow)
    end
    @user_list
  end
end

app/views/layouts/_left_navbar.html.erb
<div class="left-navbar">
  <div class="profile">
    <div class="credentials">
      <%= image_tag(current_user.photo, class: "profile-picture") %>
      <span class="full-name">
        <%= @current_user.full_name %>
      </span>
    </div>
    <div class="followings">
      <div class="followed">
        <div class="current-user-count"><%= current_user.followees.count %></div>
        <div>Following</div>
      </div>
      <div class="divider"></div>
      <div class="followers">
        <div class="current-user-count"><%= current_user.followers.count %></div>
        <div>Followers</div>
      </div>
    </div>
  </div>
  <div class="svg-links">
    <%= link_to root_path do %>
      <%= show_svg('home.svg') %>
      <span class="text">Home</span>
    <% end %>
    <%= link_to user_show_path(slug: current_user.username) do %>
      <%= show_svg('avatar.svg') %>
      <span class="text">Profile</span>
    <% end %>
  </div>
</div>

app/views/layouts/_right_navbar.html.erb
<div class="right-navbar">
  <div class="who-to-follow">
    <span class="text">Who to follow</span>
    <%= button_tag show_svg('refresh.svg'), class: 'refresh-button' %>
  </div>
  <div class="who-to-follow-results">
    <%= render 'layouts/who_to_follow' %>
  </div>
</div>

app/views/layouts/_top_navbar.html.erb
<nav class="top-navbar">
  <div class="logo"><span class="a">A</span><span class="web">web</span></div>
  <div class="svg-buttons">
    <%= button_tag show_svg('settings.svg'), class: 'svg-button dropdown-button' %>
    <div class="popup-menu">
      <%= link_to "Log out", logout_path, method: :delete %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aweb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/microposts/_error.html.erb
error<%= @error %>

app/views/microposts/_post_form.html.erb
<form class="micropost" accept-charset="UTF-8" action="javascript:void(0);" data-remote="true">
  <div class="form-group">
    <label for="text" class="text-field-label">Post something:</label>
    <input id="text" class="text-field" placeholder="Compose a new post" name="text" type="text" />
    <button name="button" type="submit" class="post-submit-button">
      <%= show_svg('paper-plane.svg') %>
    </button>
  </div>
</form>

app/views/microposts/_posts.html.erb
<div class="headline">
  All posts
</div>
<div class="timeline-posts">
  <% @posts.each do |post| %>
    <div class="timeline-post">
      <%= image_tag(post.author.photo, class: "author-profile-picture") %>
      <div class="post-content">
        <%= link_to post.author.full_name, user_show_path(slug: post.author.username), class: "full-name" %>
        <div class="author-post"><%= post.text %></div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/connection.html.erb
<div class="left">
  <%= render 'layouts/left_navbar' %>
</div>
<div class="right">
  <%= render 'layouts/top_navbar' %>
  <div class="content">
    <main>
      <%= render 'users/connection/user_list' %>
    </main>
    <%= render 'users/index/right_navbar' %>
  </div>
</div>

app/views/users/connection/_user_list.html.erb
<div class="headline"><%= @headline %></div>
<div class="scroll-wrapper">
  <% @user_list.each do |user| %>
    <div class="user">
      <%= image_tag(user.photo, class: "profile-picture") %>
      <div class="wrapper">
        <%= link_to user.full_name,
                    user_show_path(slug: user.username) %>
        <% unless user.followed_by_someone_you_follow.empty? %>
          <span>Followed by </span>
          <%= link_to user.followed_by_someone_you_follow.last.full_name,
                      user_show_path(slug: user.followed_by_someone_you_follow.last.username) %>
        <% else %>
          <span>Not followed by anyone you're following</span>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="left">
  <%= render 'layouts/left_navbar' %>
</div>
<div class="right">
  <%= render 'layouts/top_navbar' %>
  <div class="content">
    <main>
      <%= render 'users/index/tab_bar' %>
      <%= render 'microposts/post_form' %>
      <div class="main-content">
        <%= render 'microposts/posts' %>
      </div>
    </main>
    <%= render 'users/index/right_navbar' %>
  </div>
</div>

app/views/users/index/_right_navbar.html.erb
<div class="right-navbar">
  <div class="who-to-follow">
    <span class="text">Who to follow</span>
    <%= button_tag show_svg('refresh.svg'), class: 'refresh-button' %>
  </div>
  <div class="who-to-follow-results">
    <%= render 'users/index/who_to_follow' %>
  </div>
</div>

app/views/users/index/_tab_bar.html.erb
<div class="tab-bar">
  <div class="index-posts-tab tab border-bottom">
    <%= button_tag "Posts", class: 'tab-bar-button index-posts-button' %> 
  </div>
</div>

app/views/users/index/_who_to_follow.html.erb
<% @who_to_follow.each do |followee| %>
  <div class="who-to-follow-profile">
    <%= image_tag(followee.photo, class: "profile-picture") %>
    <div class="wrapper">
      <%= link_to followee.full_name, user_show_path(slug: followee.username), class: "full-name" %>
      <div class="follower-name">
        <% unless followee.followed_by_someone_you_follow.empty? %>
          <span>Followed by </span>
          <%= link_to followee.followed_by_someone_you_follow.first.full_name,
                      user_show_path(slug: followee.followed_by_someone_you_follow.first.username) %>
        <% else %>
          <span>Not followed by anyone you're following</span>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="form-signup-container">
  <%= form_for(:user , url: signup_path) do |f| %>
    <div class="logo"><span class="a">A</span><span class="web">web</span></div>
   
    <div class="form-group<%= username(@user) %>">
      <%= f.label :username %>
      <%= f.text_field :username, class: "username-signup", placeholder: username_placeholder(@user) %>
    </div>
    
    <div class="form-group<%= full_name(@user) %>">
      <%= f.label :full_name %>
      <%= f.text_field :full_name, class: "full-name-signup", placeholder: full_name_placeholder(@user) %>
    </div>
  
    <%= f.submit "Sign up", class: 'signup-button' %>
    <%= link_to "Back to Log In", login_path %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="left">
  <%= render 'layouts/left_navbar' %>
</div>
<div class="right">
  <%= render 'layouts/top_navbar' %>
  <div class="content">
    <main>
      <%= image_tag(@user.cover_image, class: "cover-image") %>
      <%= render 'users/show/tab_bar' %>
      <div class="user-main-content">
        <%= render 'microposts/posts' %>
      </div> 
    </main>
    <%= render 'users/show/right_navbar' %>
  </div>
</div>

app/views/users/show/_right_navbar.html.erb
<div class="right-navbar padding-zero">
  <div class="user-details-wrapper">
    <div class="user-details">
      <div class="wrapper">
        <% if  @user != current_user  && !@user.in?(current_user.followees) %>
          <div class="button-wrapper">
            <%= button_to '', follow_user_path(@user.id), 
                method: "POST", class: 'follow-user-button' %>
            <span></span>
            <span></span>
            <span></span>
          </div>
        <% elsif @user != current_user %>
          <div class="button-wrapper">
            <%= button_to '', unfollow_user_path(@user.id), 
                method: "POST", class: 'follow-user-button' %>
            <span></span>
            <span></span>
          </div>
        <% else %>
          <div class="place-filler"></div>
        <% end %>
        <div class="image-wrapper">
          <%= image_tag(@user.photo, class: "rounded-profile-picture") %>
        </div>
      </div>
      <div class="full-name"><%= @user.full_name %></div>
    </div>
    <div class="user-stats">
      <div class="posts">
        <div class="count"><%= @user.microposts.count %></div>
        <div class="string">Posts</div>
      </div>
      <div class="divider"></div>
      <div class="following">
        <div class="count"><%= @user.followees.count %></div>
        <div class="string">Following</div>
      </div>
      <div class="divider"></div>
      <div class="followers">
        <div class="count"><%= @user.followers.count %></div>
        <div class="string">Followers</div>
      </div>
    </div>
  </div>
  <div class="followed-by">
    <div class="who-to-follow">
      <span class="text">Followed by</span>
    </div>
    <div class="who-to-follow-results">
      <%= render 'users/show/who_to_follow' %>
    </div>
  </div>
</div>

app/views/users/show/_tab_bar.html.erb
<div class="tab-bar">
  <div class="user-posts-tab tab border-bottom">
    <%= button_tag "Posts", class: 'tab-bar-button show-posts-button' %> 
  </div>
  <div class="user-following-tab tab">
    <%= button_tag "Following", class: 'tab-bar-button show-following-button' %> 
  </div>
  <div class="user-followers-tab tab">
    <%= button_tag "Followers", class: 'tab-bar-button show-followers-button' %> 
  </div>
</div>

app/views/users/show/_who_to_follow.html.erb
<% @who_to_follow.each do |followee| %>
  <div class="who-to-follow-profile">
    <%= image_tag(followee.photo, class: "profile-picture") %>
    <div class="wrapper">
      <%= link_to followee.full_name, user_show_path(slug: followee.username), class: "full-name" %>
      <div class="handler">@<%= followee.username %></div>
    </div>
    <div class="filler"></div>
    <% unless followee == @current_user || followee.in?(@current_user.followees) %>
      <div class="button-wrapper">
        <%= button_to '', follow_user_path(followee.id), 
            method: "POST", class: 'follow-user-button' %>
        <span></span>
        <span></span>
      </div>
    <% end %>
  </div>
<% end %>